### ISSUE TITLE
Forståelse av klientMeldingId og meldingId

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/fiks-matrikkelfoering-specification#10]
Det er litt uklart nå  i [dokumentasjonen](https://developers.fiks.ks.no/tjenester/fiksprotokoll/matrikkelfoering/) og xsd'ene hvordan disse to identifikatorene skal brukes.
Spesielt kanskje i status og statussvar meldingene. Status melding tar inn klientMeldingId og svarer i statussvar melding med klientMeldingId og meldingId. Er meldingId i svaret den meldingId'en som man sendte, og får status på? KlientMeldingId kan ha vært sendt inn flere ganger.
Dette må vi få avklart og dokumentere enda tydeligere.

**Comment by torepaul** [comment]
Slik jeg og Øyvind Eid her hadde oppfattet dette har vi antatt det slik:
Unik MeldingId opprettes når en melding inneholdende en byggesak  sendes fra et byggesakssystem (med FIKS IO) til Matrikkelen for matrikkelføring første gang. Ved senere meldinger angående samme byggesak (med samme saksnummer) sendes samme MeldingsId.
Unik KlientMeldingId opprettes ved hver ny melding som sendes. Dette betyr at det opprettes en unik KlientMeldingId når en byggesak sendes første gang og en ny unik KlientMeldingId ved endring for samme byggesak.  Denne kan da brukes for å sjekke om en melding er mottatt og for å be om status for behandling.

Kan sikkert være andre oppfatninger her. Derfor viktig at dette er klart definert slik at misforståelser unngås. Det må også sjekkes at det løser alle brukstilfeller.

**Comment by jarleborsheim** [comment]
Konklusjon:

Veldig enkelt forklart så kan du som klient sette KlientMeldingId selv når du sender en melding, men det kan du ikke gjøre med MeldingId. 
MeldingId blir satt av Fiks-IO når du sender meldingen og vil dermed alltid være unik. Den må være unik da dette er id'en som brukes for å identifisere at en melding er et svar til en annen. Du får MeldingId når du sender meldingen.
KlientMeldingId anbefaler vi å bruke ved å sette den når du sender en melding, og hvis du ikke får svar på den meldingen og dermed ønsker å sende meldingen på nytt på et senere tidspunkt, så bruker du samme KlientMeldingId.  
Da kan mottaker se ut i fra KlientMeldingId at dette er en duplikat hvis de mottok første melding, men av en eller annen grunn så registrerte dere ikke svaret, eller noe annet gikk galt med svaret. 

Se mer om headerene her: https://developers.fiks.ks.no/tjenester/fiksprotokoll/fiksio/#headere-og-properties-i-meldingsutvekslingen
