### ISSUE TITLE
Hvordan skal man sende inn grunnlags melding som retter opp feil og mangler?

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/fiks-matrikkelfoering-specification#11]
Når man har sendt inn et grunnlag som inneholder delvis feil, og man så sender inn melding nr 2 for å rette opp.
Skal man sende alt på nytt? Eller bare det som fikses? 
Hvordan blir identifiseringen av kobling mellom grunnlag-melding 1 (delvis opprettet) og 2 (rette opp)? 
Ref det som står dokumentert [her](https://developers.fiks.ks.no/tjenester/fiksprotokoll/matrikkelfoering/#datamodell-for-meldinger), og spesielt det som står om "delvisFoert" i dette diagrammet: 
![datamodell_kvittering](https://github.com/ks-no/fiks-matrikkelfoering-specification/assets/832170/6656b5e6-f212-4799-9eaf-3b74c718d3fc)

Dette henger tett sammen med diskusjonen i issue #10

**Comment by jarleborsheim** [comment]
KS lager et forslag på endring i kvittering xsd. Vi slår sammen til en liste med objekter som gir forklaring pr objekt

**Comment by Arve-Corneliussen** [comment]
Slik jeg husker det var det ment at matrikkelfører skulle skrive inn en melding til saksbehandler dersom tiltaket ikke kunne føres inn i matrikkelen helt eller delvis. Antakelsen var at slike situasjoner håndteres manuelt med dialog mellom matrikkelfører og saksbehandler, dvs at de ringer/prater sammen for å løse problemet
