### ISSUE TITLE
Kodeliste for  Tiltaktype

### ISSUE THREAD

**Issue by torepaul** [ks-no/fiks-matrikkelfoering-specification#13]
I datamodellen har Tiltak to egenskaper: Tiltakid og Tiltaktype. Kodeliste for Tiltaktype er ikke definert.

Er dette denne som ligger under Byggesøknad:
https://register.geonorge.no/kodelister/byggesoknad/tiltaktype?sorting=codevalue

eller denne fra FKB-Tiltak 5.0 (Her heter den Tiltakstype)
https://register.geonorge.no/sosi-kodelister/fkb/tiltak/5.0/tiltakstypebygning

**Comment by Arvid-Beurling** [comment]
Jeg mener vi må bruke den øverste, altså den som ligger under byggesøknad, da det er denne som ligger i søknadene, og i byggesakssystemet. Så får vi matrikkeloppdateringsleverandørene heller konvertere til riktig tiltakstype i FKB Tiltak (som jo også er kraftig redusert etter FKB 5.0). Det er tiltakstype fra byggesøknad som ligger som eksempel i eksempel-xml-fila på FIKS Matrikkelføringssiden.

**Comment by jarleborsheim** [comment]
Vi legger til kodelister som json filer tilsvarende som det er gjort for andre protokoller

**Comment by jarleborsheim** [comment]
Da er kodelisten lagt til i dette specification prosjektet i json-format samt lagt til i README om kilden osv.
