### ISSUE TITLE
Kobling Kategori, tiltakstype, endring og brukstilfelle i matrikkelen

### ISSUE THREAD

**Issue by Arne-bakken** [ks-no/fiks-matrikkelfoering-specification#19]
Hvilket brukstilfelle som skal startes i matrikkelen for en matrikkelføringsmelding kommer an på en kombinasjon av kategori for saken, tiltakstype fra listen av vedtak på saken og endingsstatus for bygningen i matrkkelopplysninger

 [Kodeliste kategori](https://register.geonorge.no/kodelister/byggesoknad/s%C3%B8knadstype)

 [Kodeliste tiltakstype](https://register.geonorge.no/kodelister/byggesoknad/tiltaktype)

Følgende tiltakstyper finnes i kodelista

antenneinntil5m Antennesystem med høyde inntil 5m. Skal ikke matrikkelføres
antenneover5m Antennesystem med høyde over 5m. Skal ikke matrikkelføres
bruksendring Bruksendring. Skal kanske matrikkelføres
bruksendringhoveddel Bruksendring fra tilleggsdel til hoveddel. Skal kanske matrikkelføres
installasjonibygg Bygningstekniske installasjoner - Endring - Teknisk installasjon i bygg. Skal ikke matrikkelføres

utvendigeinstallasjoner Bygningstekniske installasjoner - Endring - Utvendige tekniske installasjoner. Skal ikke matrikkelføres
installasjonernyttanlegg Bygningstekniske installasjoner - Nytt anlegg. Skal ikke matrikkelføres
installasjonerreparasjon Bygningstekniske installasjoner - Reparasjon. Skal ikke matrikkelføres
endringanlegg Endring av anlegg. Skal ikke matrikkelføres
boligoppdeling Endring av boligenhet - Oppdeling av bolig Skal matrikkelføres

boligsammenslaing Endring av boligenhet - Sammenslåing bolig. Skal matrikkelføres
endringbyggannet Endring av bygg - Annet. Skal kanske matrikkelføres
hovedombygging Endring av bygg - hovedombygging. Skal matrikkelføres
brannskille Endring av bygg - innvendig - Brannskille i bygg. Skal ikke matrikkelføres
berekonstruksjoner Endring av bygg - innvendig - Bærekonstruksjoner i bygg. Skal ikke matrikkelføres

fundamenter Endring av bygg - innvendig - Fundamenter i bygg. Skal ikke matrikkelføres
lydskille Endring av bygg - innvendig - Lydskille i bygg. Skal ikke matrikkelføres
vatrom Endring av bygg - innvendig - Våtrom i bygg. Skal kanskkje matrikkelføres
fasade Endring av bygg - utvendig - Fasade. Skal ikke matrikkelføres
pabygg Endring av bygg - utvendig - Påbygg. Skal matrikkelføres

tilbyggunder50m2 Endring av bygg - utvendig - Tilbygg med samlet areal mindre enn 50 m2. Skal matrikkelføres
tilbyggover50m2 Endring av bygg - utvendig - Tilbygg med samlet areal større enn 50 m2. Skal matrikkelføres
underbygg Endring av bygg - utvendig - Underbygg Skal matrikkelføres
driftsbygningendringover1000m2 Endring av driftsbygning i landbruket over 1000m2 (BRA). Skal matrikkelføres
driftsbygningendringunder1000m2 Endring av driftsbygning i landbruket under 1000. Skal matrikkelføres

innhegning Innhegning. Skal ikke matrikkelføres.
mikrohus Mikrohus til boligformål - Inntil 30 m2 BRA. Skal matrikkelføres
nyttanlegg Nytt anlegg/konstruksjon. Skal ikke matrikkelføres
nyttbyggboligformal Nytt bygg - Boligformål. Skal matrikkelføres
nyttbyggdriftsbygningunder1000m2 Nytt bygg - Driftsbygning i landbruk med samlet areal under 1000 m2. Skal matrikkelføres 

nyttbyggdriftsbygningover1000m2 Nytt bygg - Driftsbygning i landbruket med samlet areal over 1000 m2 Skal matrikkelføres
nyttbyggover70m2 Nytt bygg - Over 70 m2 -Ikke boligformål Skal matrikkelføres
nyttbyggunder70m2 Nytt bygg - Under 70 m2 - ikke boligformål. Skal matrikkelføres
anleggseiendom Oppretting av matrikkelenhet - Anleggseiendom Skal ikke matrikkelføres
arealoverføring Oppretting av matrikkelenhet - Arealoverføring. Skal ikke matrikkelføres

festegrunn Oppretting av matrikkelenhet - Festegrunn over 10 år. Skal ikke matrikkelføres
grunneiendom Oppretting av matrikkelenhet - Grunneiendom. Skal ikke matrikkelføres
parkeringsplass Parkeringsplass. Skal ikke matrikkelføres
plasseringmidlertidig Plassering av midlertidige bygninger, konstruksjoner og anlegg. Skal matrikkelføres
rivinganlegg Riving av anlegg. Skal ikke matrikkelføres

rivingbygningunder70m2 Riving av bygning under 70 m2. Skal matrikkelføres
rivingdelerbygg Riving av deler av bygget. Skal kanske matrikkelføres
rivingdriftsbygninginntill1000m2. Riving av driftsbygning i landbruket inntil 1000m2. Skal matrikkelføres
rivinghelebygg Riving av hele bygg. Skal matrikkelføres
rivingtilbygginntil50m2  Riving av tilbygg inntil 50 m2. Skal kanske matrikkelføres

skiltreklamefrittstaendeliten Skilt/reklame høyde med inntil 3,5m og bredde inntil 1,5m - frittstående. Skal ikke matrikkelføres
skiltreklamefrittstaendestor Skilt/reklame høyde med over 3,5m og bredde over 1,5m - frittstående. Skal matrikkelføres
skiltreklamefasadeliten Skilt/reklame mindre enn 6,5 m2 - fasade Skal ikke matrikkelføres
fasadeskiltreklamefasadestor Skilt/reklame større enn 6,5 m2 - fasade. Skal ikke matrikkelføres
driftsbygningtilbyggover1000m2 Tilbygg til driftsbygning i landbruket med samlet area over 1000 m2 (BRA). Skal matrikkelføres

driftsbygningtilbyggunder1000m2 Tilbygg til driftsbygning i landbruket med samlet area under 1000 m2 (BRA). Skal matrikkelføres
veg Vei. Skal ikke matrikkelføres
endringdrift Vesentlig endring av tidligere drift. Skal ikke matrikkelføres
terrenginngrep Vesentlig terrenginngrep. Skal ikke matrikkelføres

Etter å ha tatt bort de som ikke skal matrikkelføres har vi disse tiltakstypene. Sorterer disse etter tilsvarede brukstilfelle i matrikkelen

**Tiltak som oppretter en ny bygning i matrikkelen**
nyttbyggover70m2 Nytt bygg - Over 70 m2 -Ikke boligformål 
nyttbyggunder70m2 Nytt bygg - Under 70 m2 - ikke boligformål. 
mikrohus Mikrohus til boligformål - Inntil 30 m2 BRA. 
nyttbyggboligformal Nytt bygg - Boligformål. Skal matrikkelføres
nyttbyggdriftsbygningunder1000m2 Nytt bygg - Driftsbygning i landbruk med samlet areal under 1000 m2. 
nyttbyggdriftsbygningover1000m2 Nytt bygg - Driftsbygning i landbruket med samlet areal over 1000 m2 
Kategori = ES eller SU brukstilfelle endre bygningsdata. Matrikkelfører må redigere data manuelt.
Kategori = IG, MB eller FA brukstilfelle Eksistrerende bygning IG, MB, FA, Legg inn vedtaksdato. Andre data må redigeres manuelt
Kategori= ET, RS eller TA. brukstilfelle ny bygning IG, ny bygning RA eller tiltak untatt søknadsplikt. Vedtaksdato legges inn. Dersom bygning har endrinsstatus ny legges den inn med alle etasjer og bruksenheter som har endringsstatus ny

**Tiltak som oppretter en ny bygningsendring i matrikkelen**
tilbyggunder50m2 Endring av bygg - utvendig - Tilbygg med samlet areal mindre enn 50 m2. 
tilbyggover50m2 Endring av bygg - utvendig - Tilbygg med samlet areal større enn 50 m2. 
underbygg Endring av bygg - utvendig - Underbygg 
pabygg Endring av bygg - utvendig - Påbygg 
driftsbygningendringover1000m2 Endring av driftsbygning i landbruket over 1000m2 (BRA). 
driftsbygningendringunder1000m2 Endring av driftsbygning i landbruket under 1000. 
driftsbygningtilbyggover1000m2 Tilbygg til driftsbygning i landbruket med samlet area over 1000 m2 (BRA). 
driftsbygningtilbyggunder1000m2 Tilbygg til driftsbygning i landbruket med samlet area under 1000 m2 (BRA). 
rivingtilbygginntil50m2  Riving av tilbygg inntil 50 m2. 
rivingdelerbygg Riving av deler av bygget. 
Kategori = ES eller SU brukstilfelle endre bygningsdata. Matrikkelfører må redigere data manuelt.
Kategori = IG, MB eller FA brukstilfelle Eksistrerende bygning IG, MB, FA, Legg inn vedtaksdato. Andre data må redigeres manuelt
Kategori = ET, RS eller TA. brukstilfelle ny bygningsendring IG, ny bygning RA eller tiltak untatt søknadsplikt. Vedtaksdato legges inn. Bør andre data fylles inn? 

**Tiltak som registreres som godkjent riving i matrikkelen**
rivingbygningunder70m2 Riving av bygning under 70 m2. 
rivingdriftsbygninginntill1000m2. Riving av driftsbygning i landbruket inntil 1000m2. 
rivinghelebygg Riving av hele bygg. 
Dersom karetori er IG brukstilfellet bygning godkjent revet Dersom kategori FA brukstilfelle bygning revet brent

**Tiltak som kanskje skal føres i matrikkelen**
bruksendring Bruksendring. 
bruksendringhoveddel Bruksendring fra tilleggsdel til hoveddel. 
vatrom Endring av bygg - innvendig - Våtrom i bygg. 
plasseringmidlertidig Plassering av midlertidige bygninger, konstruksjoner og anlegg. 

Her må matrikkelfører vurdere om tiltaket skal føres og hvilket brukstilfelle som skal brukes. Klienten må enten sende tilbake tiltakid og bygningsnummer i kvitteringen eller skal ikke matrikkelføres for tiltaket

Andre tiltak som skal føres i matrikkelen
boligoppdeling Endring av boligenhet - Oppdeling av bolig 
boligsammenslaing Endring av boligenhet - Sammenslåing bolig. 
endringbyggannet Endring av bygg - Annet. 
hovedombygging Endring av bygg - hovedombygging. 
Her må matrikkelfører vurdere om tiltaket skal føres og hvilket brukstilfelle som skal brukes. Klienten må enten sende tilbake tiltakid og bygningsnummer i kvitteringen eller skal ikke matrikkelføres for tiltaket

**Comment by Arne-bakken** [comment]
Har gjort noen justeringer 
plasseringmidlertidig Plassering av midlertidige bygninger, konstruksjoner og anlegg. Skal matrikkelføres. 
rivingtilbygginntil50m2 Riving av tilbygg inntil 50 m2. Skal matrikkelføres Dette skal matrikkelføres som en bygningendring

Riving dersom gategori er IG registreres som bygning godkjent revet. Dersom kategori er FA registreres som bygning revetbrent

**Comment by jarleborsheim** [comment]
Excel dokument med tilsvarende regler. Denne sammen med det Arne har laget vil jeg forsøke å få inn i dokumentasjonen.
[tiltakstypeRegler.xlsx](https://github.com/ks-no/fiks-matrikkelfoering-specification/files/14221290/tiltakstypeRegler.xlsx)

**Comment by jarleborsheim** [comment]
Excel ark lagt til i dokumentasjon, både filen og konvertert til markdown.
https://github.com/ks-no/fiks-matrikkelfoering-specification/tree/main/Dokumentasjon/V2/Brukstilfeller
