### ISSUE TITLE
Hva gjør man når man får bygningsinfo uten tiltaktype, og andre spørsmål.

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/fiks-matrikkelfoering-specification#20]
Hva gjør man når man får bygningsinfo uten tiltaktype
- Så lenge det er tiltakid er det ok?
- Hvis man sender inn 2 bygninger, så skal kvitteringen inneholde 2 underobjekter i 1 kvitteringsmelding.
- Tiltakid må være unik
- Tiltakid kan også settes til tallet 0 for markering

Disse brukstilfellene med forklaringer må dokumenteres

**Comment by Arne-bakken** [comment]
Forslag til implementasjon av en del tilfeller

Sak med bygninger i matrikkelopplysningner.
For hvert bygg i matrikkelopplysninger kjøres et brukstilfelle i matrikkelen. Type brukstilfelle avhenger av tiltakstype fra tiltakslista med samme tiltak id. Dersom det ikke finnes noe tiltak må bruker velge brukstilfelle selv.

Sak med bare tiltak
For hvert tiltak i tiltakslista kjøres et brukstilfelle i matrikkelen. Type brukstilfelle avhenger av tiltakstype fra tiltakslista. 

Sak uten tiltak og uten bygningner
Bruker fører saken på gamlemåten i matrikkelklienten. Når saken er ferdig justeres kvitteringsmeldingen. Bruker kan legge inn tiltak id 0 og bygningsnummer for nye eller oppdaterte bygniger. Kan også legge inn feilmeldinger eller melding om skal ikke matrikkelføres.

**Comment by jarleborsheim** [comment]
Har laget en README.md under Dokumentasjon som forklarer implementering og bruk av protokollen. Tatt med disse til @Arne-bakken og noen andre. Kom gjerne med flere forslag.

**Comment by sturtzel** [comment]
Tiltaksid 0 var spesielt tenkt for overgangsfasen fra V1 til V1 revidert. Hvis matrikkelklienten ikke har opplysninger om hvilket tiltak som er koblet til hvilket bygg, kan tiltaksid settes til 0 i kvitteringsmeldingen.

Mangler tiltaksopplysninger, kan id settes til 0.
