### ISSUE TITLE
Mulig endring til minOccurs=0 på Endring for bygning, bruksenhet og etasje

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/fiks-matrikkelfoering-specification#21]
Denne avklares til neste møte neste uke, om det må endres til minOccurs=0

**Comment by sturtzel** [comment]
Vi diskuterte med matrikkelfører i Nesbyen i ettermiddag. Hva indikerer statusen? Er den relatert til situasjonen i matrikkelen? Eller er den relatert til søknaden? Vi nybygg da være Ny, Eksisterende eller Endret når man skal matrikkelføre igangsettingstillatelsen? Trengs feltet? Kan man stole på det? Saksbehandler vil garantert sette feil verdi.

Forslag:
minOccurs 0 for endret både under bygning, bruksenhet og etasje.
Feltet blir liggende som "dødt" i overføringen og kan fjernes fra brukerdialoger.
Ved neste korsvei (når også GI-referansene kuttes) fjernes feltet.

**Comment by larseggan** [comment]
Er ikke BygningsType et sentralt begrep her i forbindelse med føring av byggesak?
Jeg mener at det fremdeles bør være opsjonelt 0..1  som i dag, og som det var i v 1.0.

**Comment by sturtzel** [comment]
Litt misvisende tittel det er feltet endring i objektet BygningType.

Den må angis for objektene BygningType, BruksenhetType og EtasjeType. Lovlige verdier er:
  <xs:simpleType name="EndringsstatusType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Eksisterende"/>
      <xs:enumeration value="Ny"/>
      <xs:enumeration value="Endret"/>
      <xs:enumeration value="Fjernet"/>
    </xs:restriction>
  </xs:simpleType>

**Comment by jarleborsheim** [comment]
Referat fra møte 10.04.2024
--- 
Det var gode diskusjoner hvor flere fikk lagt fram sine tanker om hvorfor denne endringen er ønskelig og på den andre siden hvorfor man ikke vil ha denne endringen. 

Her er et forsøk på oppsummering av argumenter for og i mot at feltet ikke skal være påkrevd.
Det kan være jeg ikke fikk med meg alt, men håper jeg har fått med det viktigste.

**For at "endring" ikke skal være påkrevd:**
- Saksbehandler får ikke nok informasjon fra søknad til å gjøre vurderingen?
- Saksbehandler er ikke opplært i dette / har ikke tid og sender det videre uansett?
- Feltet kan gjøres påkrevd i en senere versjon av protokollen (Fiks Matrikkelføring) når det er hensiktsmessig

**For at "endring" skal være påkrevd:**
- Protokollen ble designet med endringer for at det skulle være mindre manuelt arbeid. Nå blir det en vurdering som må gjøres av matrikkelfører?
- Hvordan vet matrikkelfører om det mangler noe informasjon om endringstype eller om det er komplett data som kommer?

**Comment by jarleborsheim** [comment]
Vi landet på at vi lar det stå som dette, med at `endring` er ikke påkrevd for nå. Dette håper vi at vi kan ta tilbake til required på et senere tidspunkt, men da i en ny versjon av protokollen.
Stenger denne saken
