### ISSUE TITLE
Endre Koordinat i giFellesGeometri20120131.xsd tilsvarende som i Fiks-Plan?

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/fiks-matrikkelfoering-specification#8]
Vi sendte en mail 18.08 hvor vi ønsker å få innspill til dette med å koordinere datatypen for punkt/posisjon mellom alle protokollen. 

For Fiks-Plan gjorde vi en forenkling for å følge GeoJson. 
Se gjerne issuet her: https://github.com/ks-no/fiks-plan-specification/issues/26

Vi har et tilsvarende issue for Fiks-Arkiv hvor det dukket opp et spørsmål om det blir riktig å gjøre det som for Fiks-Plan eller om det er noen argumenter mot dette.
Se gjerne issuet her: https://github.com/ks-no/fiks-arkiv-specification/issues/157

Bør vi endre Koordinat i giFellesGeometri20120131.xsd tilsvarende?

**Comment by larseggan** [comment]
Hei,

Jeg mener vi bør beholde UTM Euref89 som koordinatsystem.
Det er litt misvisende med WGS84 generelt, jeg tror dere her mener geografiske koordinater, men ser bort fra datum.
I Norge (og i resten av Europa) forholder vi oss til referanseramme Euref89.
Men WGS84 er den virkelige koordinaten på nå-tidspunkt, og her er det en forskjell.
Se også https://register.geonorge.no/epsg-koder

Angående GeoJSON så står det som blir sagt at det er WGS84 som er standard, men det er fult mulig å angi koordinatsystem på GeoJSON-format (crs) bare man er enig.
Det er det vi gjør bl. annet i NGIS OpenAPI.

Og vi må ta hensyn til datasett med høyder.
Eksempelvis disse to EPSG 4258 og EPSG 5942 (geografiske koordinater med og uten høydereferanseNN200):
![image](https://github.com/ks-no/fiks-matrikkelfoering-specification/assets/11415599/df469153-d0e2-4511-887c-c43c0585d94a)

**Comment by larseggan** [comment]
Det er UTM Euref89 som benyttes av tidligere Geointegrasjon-standard.
Det samme for Matrikkelen og for Sentral FBK.
Sone 32 for sør-Norge, sone 33 for Nordland og Troms, sone 35 for Finnmark.
Det finnes nå en modernisert tjeneste fra Kartverket som tar seg av koordinattransformasjoner:
https://ws.geonorge.no/transformering/v1/

**Comment by jarleborsheim** [comment]
Som det ble påpekt i Slack-kanalen vår bør vi nok ikke endre i `giFellesGeometri20120131.xsd` filen. Det vi ønsker er å legge til.

**Comment by torkjetil** [comment]
Kravene i nye NPAD Planforslag er https://www.regjeringen.no/contentassets/8a9cc8f0885d4f5cb9f32d1f7e3f385e/npad_regplanforslag_19_sept_2023.pdf  er: 
![image](https://github.com/ks-no/fiks-matrikkelfoering-specification/assets/366886/19b6be20-361d-4473-aa25-7d8aafa654d0)
