### ISSUE TITLE
Rydde i referanser og navn på fellesskjema

### ISSUE THREAD

**Issue by jarleborsheim** [ks-no/fiks-matrikkelfoering-specification#9]
Vi burde ikke ha navn som heter giintegrasjon osv på skjema og url burde gå til den nye standarden fiks matrikkelføring.
F.eks. burde ikke felleskjema filer ha navn som peker til en eldre standard: [giFellesGeometri20120131.xsd](https://github.com/ks-no/fiks-matrikkelfoering-specification/blob/main/Schema/V2/giFellesGeometri20120131.xsd)

Vi burde:
- Rydde vekk felles skjema som ikke trengs og erstatte heller med bare de fellestypene vi bruker i protokollen
- Urler til skjema bør peke til en KS side med Fiks Matrikkelføring 

Vil dette føre til at vi må bumpe til v3, eller kan vi gjøre denne endringen på v2?
Kartlegging av implementasjonsgrad kan hjelpe til for denne avgjørelsen. En mail vil bli sendt til Fiks Matrikkelføring deltakerne.

**Comment by sturtzel** [comment]
Litt for sent nå, men siden tjenesten likevel ble oppdatert...

**Comment by jarleborsheim** [comment]
Denne må eventuelt komme med neste versjon
